# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FBP9lcmcgAdBul_8kD39WMLcXScZ6Rit
"""

# -*- coding: utf-8 -*-
"""Untitled2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1FBP9lcmcgAdBul_8kD39WMLcXScZ6Rit
"""

import random
n=1000000 #no of times the experiment is conducted
i=0
p=0 #no of cases favourable for first black ball
#caluclating theoritical probabilities
P=1/2 #P2 is theoritical probability of selecting second ball as black given first one is black
print('theoritical probability of taking second ball from the urn given first ball is black is:',P)
#caluclating simulated probabilities
k=0 #no of cases favorable for second red ball given first is white
while i<n:
  x=random.randint(1,6)#since 1st ball(black) is taken out remaining balls count is 6
  if x<=3:#in that 6 assume 3 white balls represent first 3 numbers 
    k=k+1
  i=i+1
P_1=k/n
print('simulated probability of taking second red ball given first ball is white is: ',P_1)
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About